namespace Projeto.Migrations
{
    using Projeto.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Projeto.Models.ProjetoContext>
    {
        public Configuration()
        {
            //é possível fazer automaticamente o RECRIAR da base de dados
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(Projeto.Models.ProjetoContext context)
        {
            var clientes = new List<Clientes> {
    new Clientes {ID=1,  NIF="230884873", Morada="Rua Dom Pedro v São Victor 3 Braga", Nome="Alberta Afonso", CodPostal=4714501},
    new Clientes {ID=2,  NIF="247975958", Morada="Avenida da Liberdade São José de São Lázaro 424 Braga", Nome="Dália Alcántara", CodPostal=4714502 },
    new Clientes {ID=3,  NIF="245386700", Morada="Avenida de Trezeste Celeirós", Nome="Eunice Nieto", CodPostal=4709001},
    new Clientes {ID=4,  NIF="270253777", Morada="Rua Professor Elísio Moura São João da Madeira", Nome="Miguel Alancastre", CodPostal=3700323},
    new Clientes {ID=5,  NIF="204519926", Morada="Rua Doutor Alexandre Faria Bairro da Estação Bragança", Nome="Mónica Lousã", CodPostal=5301851},
    new Clientes {ID=6,  NIF="247499978", Morada="Alameda de Santa Apolónia Núcleo urbano Bragança", Nome="Fernão Vargas", CodPostal=5301855},
    new Clientes {ID=7,  NIF="275294323", Morada="Rua dos Combatentes da Grande Guerra Bragança", Nome="Ramiro Gonçalves", CodPostal=5301861}
};

            var exemplares = new List<Exemplares> {
    new Exemplares {NumSerie=0347525962, Garantia=new DateTime(2019,05,30)},
    new Exemplares {NumSerie=0147586667, Garantia=new DateTime(2019,07,23)},
    new Exemplares {NumSerie=0919366264, Garantia=new DateTime(2019,07,30)},
    new Exemplares {NumSerie=1112474955, Garantia=new DateTime(2019,08,02)},
    new Exemplares {NumSerie=0507273638, Garantia=new DateTime(2019,08,05)},
    new Exemplares {NumSerie=2025424548, Garantia=new DateTime(2019,08,13)},
    new Exemplares {NumSerie=2032334666, Garantia=new DateTime(2019,08,19)},
    new Exemplares {NumSerie=0312131853, Garantia=new DateTime(2019,08,21)},
    new Exemplares {NumSerie=1826343669, Garantia=new DateTime(2019,09,04)},
    new Exemplares {NumSerie=2128354146, Garantia=new DateTime(2019,09,13)},
    new Exemplares {NumSerie=0107111323, Garantia=new DateTime(2019,09,20)},
    new Exemplares {NumSerie=0506071923, Garantia=new DateTime(2019,10,15)},
    new Exemplares {NumSerie=1222343960, Garantia=new DateTime(2019,10,18)},
    new Exemplares {NumSerie=0412232853, Garantia=new DateTime(2019,11,14)},
    new Exemplares {NumSerie=1861666768, Garantia=new DateTime(2019,11,19)},
    new Exemplares {NumSerie=1821404853, Garantia=new DateTime(2019,06,03)}

};

            var produto = new List<Produto> {
    new Produto {ID=1,Plataforma="PS2/PSP", NomeProduto="Persona 3", Preco=31.99F, Stock=20, Descricao="A história de Persona 3 realiza-se em uma cidade japonesa moderna, construída e financiada pela Kirijo Corporation. Devido aos acontecimentos ocorridos no passado, há uma 'Dark Hour': um período de tempo que existe entre a meia-noite e o próximo dia que só poucas pessoas podem ver; aqueles que não estão conscientes se encontram congelados em caixões. A Dark Hour traz a curva da realidade; a Gekkoukan High School, onde a maioria dos personagens frequentam a escola durante o dia, à noite se torna um enorme torre com labirintos chamada 'Tartarus', que possui bestas chamadas Shadows que estão à vagar e proteger certas áreas, às que se encontram fora do Tartarus, predam sobre as mentes das pessoas ainda consciente durante esse tempo, deixando as vítimas em estado quase catatônico fora da Dark Hour. ", ImagemProd="pesona_3.jpg"},
    new Produto {ID=2,Plataforma="PSP/PS1/PS2/PS3/PS4/DS/3DS/Switch/PC", NomeProduto="Final Fantasy 7",  Preco=12.99F, Stock=35, Descricao="Dentro dos Subúrbios de Midgar reside a organização eco-terrorista AVALANCHE, liderada por Barret Wallace, um antigo habitante de Corel, uma cidade destruída pela Shinra. O grupo AVALANCHE aluga um mercenário chamado Cloud Strife, que diz ser um antigo membro da força especial de elite da Shinra, SOLDIER.Cloud é atormentado por perturbações psíquicas e, a princípio, demonstra pouco interesse à causa do AVALANCHE; de acordo com ele mesmo, só está interessado no dinheiro. Outros membros do AVALANCHE incluem Tifa Lockhart, uma amiga de infância de Cloud a qual ele fez uma promessa de protegê-la há anos atrás, antes de deixarem Nibelheim, sua cidade natal, e Jessie, Biggs e Wedge.", ImagemProd="final_fantasy_vii.jpg"},
    new Produto {ID=3,Plataforma="PS1/PC", NomeProduto="Metal Gear Solid", Preco=19.99F, Stock=16, Descricao=" O protagonista pode usar várias armas, das quais muitas existem no mundo real. Em certos pontos do jogo ele tem de lutar com vários chefes que usualmente tem diferentes habilidades sobre-humanas ou sobrenaturais. Em alguns jogos, o penúltimo chefe é a última encarnação do Metal Gear, com os seguintes chefes sendo confrontos um-contra-um com o principal antagonista do jogo.", ImagemProd="metal_gear_solid.jpg"},
    new Produto {ID=4,Plataforma="PS2", NomeProduto="Kingdom Hearts 2", Preco=19.99F, Stock=25, Descricao="Kingdom Hearts II é um jogo eletrônico RPG de ação desenvolvido e publicado pela Square Enix. É o terceiro título da série Kingdom Hearts, uma colaboração entre a Square Enix e a The Walt Disney Company, e foi lançado exclusivamente para o PlayStation 2 em dezembro de 2005 no Japão, março de 2006 na América do Norte e setembro de 2006 na Europa. Na história, Sora parte à procura de seus amigos perdidos. ", ImagemProd="kingdom_hearts_ii.jpg"},
    new Produto {ID=5,Plataforma="PC/XBox/PS3", NomeProduto="Assassins Creed",   Preco=13.90F, Stock=31, Descricao="Assassin's Creed é uma série de videogame. A premissa central envolve-se a partir da rivalidade entre duas sociedades secretas ancestrais: os Assassinos que desejam a paz através do livre arbítrio e os Templários, que têm o objetivo de dominar o mundo . Ambos tiveram uma relação indireta com uma espécie que viveu antes dos humanos, cuja sociedade foi destruída por uma gigantesca tempestade solar. Misturando personagens e ficção histórica com eventos e figuras reais, a ordem cronológica dos jogos começa em 2012, e fala de Desmond Miles, um jovem que com a ajuda do Animus (uma máquina que permite ver as suas 'memórias ancestrais'), explora as memórias de alguns dos mais proeminentes Assassinos da história. ", ImagemProd="assassin_creed.jpg"},
    new Produto {ID=6,Plataforma="PS3/XBox/PC/PS4/Switch", NomeProduto="Dark Souls",       Preco=29.99F, Stock=12, Descricao="Dark Souls se passa primariamente no reino fictício de Lordran, onde os jogadores assumem o papel de um personagem denominado 'Chosen Undead' que, segundo lendas, seria responsável pela quebra de uma maldição que torna incapazes de morrer aqueles que são afligidos por uma misteriosa marca negra. O jogo é inspirado fortemente pela temática medieval, com a presença de deuses e seres fantásticos, inseridos em um mundo decadente e punitivo. A estrutura de apresentação da história é subjetiva, dando-se basicamente através da descrição de itens ou em interações com NPCs, possibilitando margem para diversas interpretações acerca de toda a mitologia presente no jogo.", ImagemProd="dark_souls.jpg"},
    new Produto {ID=7,Plataforma="PS4/PS3", NomeProduto="Persona 5",        Preco=49.99F, Stock=34, Descricao="Persona 5 é um RPG desenvolvido pela Atlus. O jogo é cronologicamente a sexta edição da série Persona, que faz parte principalmente da franquia Megami Tensei. Foi lançado para o PlayStation 3 e PlayStation 4 no Japão em setembro de 2016[1] e em todo o mundo em abril de 2017,[2] onde foi publicado pela Atlus no Japão e na América do Norte, e pela Deep Silver na Europa e Austrália. Persona 5 acontece na Tóquio de hoje e segue o protagonista Joker após sua transferência para a Academia Shujin após ser colocado em liberdade condicional por um assalto do qual ele foi falsamente acusado. Durante o curso de um ano escolar, ele e outros estudantes despertam seus poderes de Persona, tornando-se um grupo de justiceiros secretos conhecidos como os Ladrões Fantasmas de Corações.", ImagemProd="persona_5.jpg"},
    new Produto {ID=8,Plataforma="PS4/XBox", NomeProduto="Kingdom Hearts 3", Preco=69.99F, Stock=33, Descricao="A conceitualização do jogo começou por volta de 2006, logo após o lançamento japonês de Kingdom Hearts II: Final Mix, com o jogo sendo apenas confirmado oficialmente durante a Electronic Entertainment Expo de 2013 após anos de rumores e especulações. Kingdom Hearts III se passa após os eventos mostrados em Kingdom Hearts 3D: Dream Drop Distance, tendo o protagonista Sora se juntando com o Pato Donald, Pateta, Rei Mickey e Riku em sua busca dos sete guardiões da luz e da 'Chave para Retornar Corações' enquanto tentam frustrar os planos do Mestre Xehanort de iniciar uma guerra devastadora. Sua jornada os faz cruzar caminhos com personagens e visitar mundos baseados em diferentes propriedades da Disney e da Pixar. O jogo foi construído usando a Unreal Engine 4. ", ImagemProd="kingdom_hearts_iii.jpg"},
    new Produto {ID=9,Plataforma="PS4/PC/XBox", NomeProduto="Nier: Automata",    Preco=36.74F, Stock=27, Descricao="Nier: Automata é um RPG eletrónico de ação que se passa em uma Terra pós-apocalíptica milhares de anos depois dos eventos mostrados no Nier original. O jogador assume o controle de andróides de combate em um ambiente de mundo aberto. Além da navegação a pé, é possível usar itens especiais a fim de chamar animais selvagens para serem usados como montarias, com máquinas voadoras estando disponíveis em certas ocasiões para combater inimigos. A câmera muda de posição de sua visão em terceira pessoa padrão para uma vista aérea ou lateral durante a navegação por certos ambientes. Algumas das áreas incluem quebra-cabeças de plataforma que requerem que o jogador navegue ao pular entre plataformas ou obstáculos. O jogador pode realizar missões paralelas para personagens não jogáveis encontrados em locais centrais.", ImagemProd="nier_automata.jpg"},
    new Produto {ID=10,Plataforma="PS1/PC/DS", NomeProduto="Resident Evil",    Preco=19.99F, Stock=9, Descricao="O enredo de Resident Evil inicia em torno de uma série de casos de homicídio envolvendo canibalismo ocorridos em Arklay Mountain (Montanhas Arklay), ao norte da cidade fictícia Raccoon City em 1998. O S.T.A.R.S (Special Tactics And Rescue Service - Serviço de Resgate e Táticas Especiais) é designado para investigar a fonte de tais assassinatos. O grupo era formado por duas equipes, Bravo Team e Alpha Team. A Equipe Bravo é designada para investigar os incidentes, contudo o grupo acaba desaparecendo misteriosamente. A equipe Alpha é enviada em uma missão de resgate, mas acaba sendo atacado e seus membros são forçados a se refugiarem em uma mansão abandonada, onde o grupo acaba se deparando com zumbis e outras criaturas, levando-os a descobrir os cadáveres de seus companheiros da Equipe Bravo na casa.", ImagemProd="resident_evil.jpg"},
    new Produto {ID=11,Plataforma="PSP", NomeProduto="Dissidia FF",      Preco=14.99F, Stock=10, Descricao="O jogo possui personagens desde o primeiro título da série e se centra em um grande conflito entre Cosmos, a deusa da harmonia, e o Chaos, o deus da discórdia. Os dois convocam diversos guerreiros para lutarem no seu lado em sua décima terceira guerra. O jogador controla durante a história os dez guerreiros escolhidos por Cosmos, que são os protagonistas dos dez primeiros jogos principais da série Final Fantasy. A versão internacional e norte-americana também dá acesso a outras funcionalidades como um modo arcade.", ImagemProd="dissidia.jpg"},
    new Produto {ID=12,Plataforma="PS2/XBox/Switch/PC/PS3/PS4", NomeProduto="Okami",            Preco=20.76F, Stock=31, Descricao="O jogo se passa no Antigo Japão e começa com um flashback de 100 anos antes de seu presente. O flashback conta a história de como Shiranui, um lobo branco, e Nagi, um guerreiro, lutaram juntos para derrotar a serpente de oito cabeças Orochi para salvar o Vilarejo de Kamiki e a dama Nami, a amada de Nagi. Shiranui e Nagi não são capazes de derrotar o dragão, mas só de aprisioná-lo numa caverna. 100 anos depois, um descendente de Nagi, Susano, acidentalmente quebra o selo de Orochi, e ele então escapa e lança uma maldição sobre a Terra, destruindo toda a vida existente. Sakuya, um espírito das árvores e guardiã do Vilarejo de Kamiki, invoca a deusa do Sol e reencarnação de Shiranui Amaterasu, e pede para que ela remova a maldição que cai sobre a Terra.", ImagemProd="okami.jpg"},
    new Produto {ID=13,Plataforma="PSP", NomeProduto="Kingdom Hearts Birth by Sleep", Preco=65.49F, Stock=24, Descricao="O jogo utiliza um sistema de batalha reformulado em relação aos títulos anteriores da série, possuindo a adição de novos elementos. Ele serve como prequela de toda a história da franquia, passando-se dez anos antes do primeiro jogo Kingdom Hearts. O enredo centra-se em Terra, Aqua e Ventus, personagens que fizeram uma breve aparição em Kingdom Hearts II, em sua procura para encontrar o desaparecido Mestre Xehanort e proteger os mundos de terríveis criaturas.", ImagemProd="khbbs.png"},
    new Produto {ID=14,Plataforma="Switch", NomeProduto="Pokémon Let's Go Eevee", Preco=48.99F, Stock=14, Descricao="Os jogos se passam na região de Kanto, e contam com elementos comuns da franquia, como batalhar contra treinadores de personagens não jogáveis e líderes de ginásio com Pokémon capturados. O sistema de captura utiliza um mecanismo diferente baseado no jogo para plataformas móveis Pokémon Go em oposição ao tradicional sistema de batalha, onde os jogadores podem jogar Pokébolas em um Pokémon selvagem usando os controles de movimento do Joy-Con, mas não podem atacá-los.", ImagemProd="pokemon_lets_go_eevee.png"},
    new Produto {ID=15,Plataforma="PC/XBox/Switch", NomeProduto="Cuphead", Preco=19.99F, Stock=7, Descricao="Nas ilhas fictícias Inkwell, Cuphead e seu irmão Mugman são dois garotos amantes da diversão que vivem sob o olhar atento de seu avô Elder Kettle. Contra os avisos do ancião, os irmãos entram no Cassino do Diabo e começam a jogar dados . Quando eles vão em uma série de vitórias, o próprio diabo se oferece para aumentar as apostas. Se Cuphead e Mugman puderem ganhar mais uma rodada, eles receberão todo o dinheiro no cassino; se não, o diabo levará suas almas. Cuphead perde no jogo de dados e ele e Mugman imploram por misericórdia. O Diabo faz um acordo com eles: coletar os 'contratos de alma' que significam sua posse das almas de seus devedores fugitivos até a meia-noite do dia seguinte, assim ele deixará que Cuphead e Mugman fiquem com suas almas.", ImagemProd="cuphead.jpg"},
    new Produto {ID=16,Plataforma="Switch", NomeProduto="Legend of Zelda Breath Of the Wild", Preco=69.99F, Stock=41, Descricao="The Legend of Zelda: Breath of the Wild se passa no fim da cronologia de The Legend of Zelda, depois de todos os outros jogos. No passado, por repetidas vezes, o mal conhecido como Calamity Ganon ameaçou o Reino de Hyrule, sempre sendo derrotado pela princesa Zelda, descendente da deusa Hylia, com a ajuda de seu fiel protetor Link. Hyrule com o passar dos séculos tornou-se uma civilização avançada, protegida por quatro Feras Divinas – maquinas animalescas enormes – e por um exército de Guardiões, armas robóticas autônomas. Quando Ganon retornou mais uma vez, quatro grandes guerreiros receberam o título de Campeão e pilotaram as Feras Divinas, protegidos por Zelda, Link e pelos Guardiões. ", ImagemProd="legend_of_zelda_bresth_of_the_wild.jpg"},
    new Produto {ID=17,Plataforma="PS4", NomeProduto="Uncharted 4: A Thief's End", Preco=14.99F, Stock=45, Descricao="Três anos depois dos eventos ocorridos em Uncharted 3: Drake's Deception, Nathan 'Nate' Drake (Nolan North) desistiu de ser um caçador de tesouros e tem uma vida normal com Elena Fisher (Emily Rose). A sua rotina é interrompida quando Samuel 'Sam' Drake (Troy Baker), o seu irmão mais velho que supostamente estaria morto, entra na sua vida. Sam diz-lhe que precisa da ajuda de Drake para encontrar um artefacto muito antigo relacionado com o tesouro do pirata Henry Avery; já que sua vida depende disso. Drake já o tinha tentado o encontrar no passado, mas nunca chegou a qualquer conclusão, e assim é forçado a entrar de novo no mundo dos ladrões, com promessa de aventuras e a oportunidade de ajudar um familiar.", ImagemProd=""},
    new Produto {ID=18,Plataforma="PC/XBox/PS4", NomeProduto="Metro Exodus", Preco=69.99F, Stock=12, Descricao="Metro Exodus é um jogo eletrônico de tiro em primeira pessoa com elementos de survival horror e stealth. Situado no terreno baldio pós-apocalíptico da antiga Federação Russa, o jogador deve lidar com os novos perigos e se envolver em combate contra criaturas mutantes, assim como contra humanos hostis. O jogador empunha um arsenal de armamento feito à mão que pode ser personalizado através de materiais de looting e de um sistema de crafting. O jogo apresenta uma mistura de níveis lineares e ambientes de sandbox. Também inclui um sistema climático dinâmico, um ciclo de dia e noite e ambientes que mudam com as estações conforme a história avança.", ImagemProd=""}

};
            

            var plataforma = new List<Plataforma> {
    new Plataforma {ID=1, Nome="PS1", Imagem="ps1.png"},
    new Plataforma {ID=2, Nome="PS2", Imagem="ps2.png"},
    new Plataforma {ID=3, Nome="PS3", Imagem="ps3.png"},
    new Plataforma {ID=4, Nome="PS4", Imagem="ps4.png"},
    new Plataforma {ID=5, Nome="Switch", Imagem="switch.png"},
    new Plataforma {ID=6, Nome="NDS", Imagem="nds.png"},
    new Plataforma {ID=7, Nome="PSP", Imagem="psp.png"},
    new Plataforma {ID=8, Nome="PC", Imagem="pc.png"},
    new Plataforma {ID=9, Nome="XBox", Imagem="xbox.png"},

};

        }
    }
}
